name: Build and Deploy frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd BEARMAX-V2
            git stash
            git stash drop
            git pull
            cd Client
            npm install
            npm run build
            rm -r /var/www/bearmaxcare.com/html/*
            mv dist/* /var/www/bearmaxcare.com/html
            rm -r ~/BEARMAX-V2/Client/node_modules
            rm -r ~/BEARMAX-V2/Client/dist
            rm -r ~/BEARMAX-V2/node_modules