name: Build and Deploy backend and frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            docker stop $(docker ps -a -q)
            docker system prune -a
            yes | head -1
            cd BEARMAX-V2
            git pull
            cd Server
            docker build -t bearmax-backend .
            docker run --env-file .env -d -p 8080:8080 bearmax-backend
            cd ../Client
            npm install
            npm run build
            rm -r /var/www/bearmaxcare.com/html/*
            mv dist/* /var/www/bearmaxcare.com/html